articles/urls.py
from django.urls import path

from .views import (
    article_search_view,
    article_create_view,
    article_detail_view
)

app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),
]

recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_update_view,
    recipe_delete_view,
    recipe_detail_hx_view,
    recipe_ingredient_update_hx_view,
    recipe_incredient_delete_view,
    recipe_ingredient_image_upload_view


)

app_name='recipes'

urlpatterns = [
    path("", recipe_list_view, name='list'),
    path("create/", recipe_create_view, name='create'),
    path("<int:id>/", recipe_detail_view, name='detail'),
    path("<int:id>/edit/", recipe_update_view, name='update'),
    path("<int:parent_id>/ingredient/<int:id>/delete/", recipe_incredient_delete_view, name='ingredient-delete'),
    path("<int:id>/delete/", recipe_delete_view, name='delete'),
    # path("<int:parent_id>/image-upload/", recipe_ingredient_image_upload_view,name='image-upload'),
    path("<int:parent_id>/image-upload/", recipe_ingredient_image_upload_view, name='recipe-ingredient-image-upload'),
    
    path("hx/<int:id>/", recipe_detail_hx_view, name='hx-detail'),
    path("hx/<int:parent_id>/ingredient/<int:id>/", recipe_ingredient_update_hx_view, name='hx-ingredient-detail'),
    path("hx/<int:parent_id>/ingredient/", recipe_ingredient_update_hx_view, name='hx-ingredient-create')
]

tryDjangoProject/urls.py
from django.contrib import admin
# from django.urls import path
from django.urls import include, path


from .views import home_view
# from articles import views
# from articles.views import (
#     article_create_view,
#     article_search_view,
#     article_detail_view
# )
from accounts.views import (
    login_view,
    logout_view,
    register_view)

from search.views import search_view

urlpatterns = [

    path('admin/', admin.site.urls),

    path('',home_view),
    # path('articles/<int:id>',article_detail_view),
    # path('articles/<slug:slug>/', article_detail_view),
    # path('articles/',article_search_view),
    # # path('articles/create/',article_create_view),
    # path('articles/create/', article_create_view, name='article-create'), #reverse URLs
    # path('articles/<slug:slug>/', article_detail_view, name='article-detail'), #reverse URLs
    path('login/',login_view),
    path('logout/',logout_view),
    path('register/',register_view),
    path('search/', search_view, name='search'),
    
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://unpkg.com/htmx.org@1.5.0"></script>
    <!-- <style>

        static files me daal ke use kr rhe hai isko
        .htmx-indicator {
            display: none;
        }
        .htmx-request .htmx-indicator {
            display: inline;
        }
        .htmx-inverted-indicator {
            display: inline;
        }
        .htmx-request .htmx-inverted-indicator {
            display: none;
        }
    </style> -->
    <link rel='stylesheet' href='{% static "recipes/recipes-htmx.css" %}' />
    <!-- <link rel='stylesheet' href="static/recipes/recipes-htmx.css"  /> ye wala andar wale static ke liye hai(pr ye overwrite ho jayega) -->
</head>

<body>
    <h1>Hello World!<h1>
           
            <!-- <form action="/articles/" method="GET">
        <input type="text" name="q">
        <input type="submit">
    </form>    to made search more dynamic -->
            {% include 'search/search-form.html' %}


            {% block content %}
            {% endblock content%}

            <script>
                document.body.addEventListener("htmx:configRequest", (event) => {
                    event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
                })

        // for the htmx in delete recipe and recipe ingredient
            </script>

</body>

</html>

templates/home-view.html
<!-- use as template inheritance -->
{% extends "base.html"%}

{% block content %}

<h1>Hello {{title}}!.</h1>
<p1>{{content}} having id {{id}}.</p1>

<br><br>

<a href='{% url "recipes:list" %}'>GO TO RECIPES</a>
<br>
<br>
<a href='{% url "articles:create" %}'>Create Article</a>
<br>
<a href='{% url "articles:detail" slug="hello-world" %}'>Hello world article</a>
<br>

<ul>
    {% for x in my_list %}
    <li> {{x}} </li>
    {% endfor %}
</ul>

<div> 
<ul>
    {% for x in object_list %}
    <!-- <li><a href="/articles/{{x.id}}" target="_main">{{x.title}}-{{x.content}}</a></li> -->
    <!-- <li><a href='/articles/{{ x.slug }}/'>{{ x.title }} - {{ x.content }}</a></li> -->
    <li><a href='{{ x.get_absolute_url }}'>{{ x.title }} - {{ x.content }}</a></li>
    {% endfor %}

    <!-- /articles/{{x.id}}-ye sahi cheez hai,isse apne database ka address samajh aa rha hai -->
</ul>
</div> 


<div>
    <h2><a href="articles/create/">Click here to create new articles.</a></h2>
    <h2><a href="login/">Click here to login.</a></h2>
</div>  


{% endblock content%}

templates/image-form.html
{% extends "base.html" %}


{% block content %}

<form action='.' method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button style='margin-top:10px;' type='submit' >Upload Image</button>
</form>

{% endblock content %}